// <autogenerated>
//   This file was generated by T4 code generator CreateIntegrationTestsScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace MDM.Client.Sample.IntegrationTests.Checkers
{
    using EnergyTrading.Mdm.Contracts;
    using EnergyTrading.Test;

    public class SourceSystemDetailsChecker : NCheck.Checker<SourceSystemDetails>
    {
        public SourceSystemDetailsChecker()
        {
			Compare(x => x.Name);
		}
    }
}